export const DELETE_BOOK = 'DELETE_BOOK';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const CHANGE_BOOK_LIST = 'CHANGE_BOOK_LIST';
export const FETCH_BOOKS = {
    REQUEST: 'FETCH_BOOKS_REQUEST',
    SUCCESS: 'FETCH_BOOKS_SUCCESS',
    FAILURE: 'FETCH_BOOKS_FAILURE'
};

